services:
  finance-api:
    build:
      context: .
      dockerfile: Finance.Api/Dockerfile
    container_name: finance-api
    env_file:
      - .env.local
    environment:
      - Serilog__WriteTo__0__Args__serverUrl=http://finance-seq:5341
      - ASPNETCORE_DataProtection__KeyManagement__XmlRepository__Directory=/root/.aspnet/DataProtection-Keys
    ports:
      - "5000:8080"
    depends_on:
      finance-sqlserver:
        condition: service_healthy
      finance-postgre:
        condition: service_started
      finance-redis:
        condition: service_started
    volumes:
      - finance_keys:/root/.aspnet/DataProtection-Keys
    networks:
      finance-network:

  finance-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: finance-sqlserver-db
    env_file:
      - .env.local
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - finance_sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '${DB_SA_PASSWORD}' -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s
    networks:
      finance-network:
    
  finance-postgre:
    image: postgres:alpine
    container_name: finance-postgre-db
    env_file:
      - .env.local
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD}
      - POSTGRES_DB=FinanceReadDb
    ports:
      - "5432:5432"
    networks:
      - finance-network

  finance-seq:
    image: datalust/seq:latest
    container_name: finance-seq
    env_file:
      - .env.local
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=${SEQ_ADMIN_PASSWORD}
    ports:
      - "5341:80" 
    networks:
      finance-network:
    
  finance-redis:
    image: redis:alpine
    container_name: finance-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      finance-network:

volumes:
  finance_sql_data:
  finance_keys:

networks:
  finance-network:
